package Configuracao
import configuracao.Conexao

fun main() {

    val jdbcTemplate = Conexao().getJdbcTemplate()

/*
método execute() -> executa qualquer tipo de instrução SQL
OBS: O ";" ao final da instrução é opcional, porém, se houverem
     mais de 1 instrução SQL, deve ter o ";" ao final de cada uma
 */
    jdbcTemplate.execute("""
        create table IF NOT EXISTS Carro (
            idCarro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Modelo VARCHAR(20) NOT NULL,
            Ano INT NOT NULL,
            Potencia DECIMAL(4,1) NOT NULL
        );
    """)

}