CREATE DATABASE champions;
USE champions;

CREATE TABLE usuario (
	idUsuario INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(45),
	email VARCHAR(45),
	senha VARCHAR(15),
	fkTimeC INT,
    FOREIGN KEY (fkTimeC) REFERENCES TimeCoracao (idTimeC),
    fkTimeUCL INT,
    FOREIGN KEY (fkTimeUCl) REFERENCES TIMESUCL (idTimeUCL)
);
				
INSERT INTO usuario VALUES (NULL,'Pedro','pedro@ucl.com','pedrinho123',300,2001),
                           (NULL,'Wilker','wilker@sptech.school','1234',301,2004),
                           (NULL,'Thais de frança','thais@sptech.school','1234',302,2013),
                           (NULL,'Mauricio','mauricio@sptech.school','123',303,2006),
                           (NULL,'Eduardo Begattini','eduardobegattini@gmail.com','54321',304,2016),
                           (NULL,'Mateus','mateus@sptech.school','12345',305,2004),
                           (NULL,'Luigi','lulu@gmail.com','12345',306,2000),
                           (NULL,'Leonardo Pinho','leonardo.pinho@sptech.school','1234',307,2004),
                           (NULL,'Gustavo','gusta.goncalves@hotmail.com','12345',308,2002),
                           (NULL,'Irineu','irineu@gmail.com','1234',309,2016),
                           (NULL,'Gabriel Bordin','biel@gmail.com','123',310,2014),
                           (NULL,'Nicolas','nick@gmail.com','1122',311,2013),
                           (NULL,'Rafa','rafael.oliveira@sptech.school','rafa',312,2006),
                           (NULL,'Ruy','ruy@gmail.com','1234',313,2002),
                           (NULL,'Michelly','Michelly@gmail.com','1234',314,2002),
                           (NULL,'Rafaela','rafaela.dias@sptech.school','123',315,2000),
                           (NULL,'Gabriel','gabriel.antonio@hotmail.com','ascd123',316,2007),
                           (NULL,'Patrick','patrick@gmail.com','1234',317,2007),
                           (NULL,'Lourenzo Mota','lourenzo.silva@gmail.com','1234567',318,2000),
                           (NULL,'Ezequiel','ezequiel@gmail.com','0907',319,2004),
                           (NULL,'Vitinho','victorlage@gmail.com','ODLA',320,2001),
                           (NULL,'Fabio','fabo@gmail.com','123',321,2002),
                           (NULL,'Kaique','kaique@gmail.com','1234',322,2001),
                           (NULL,'Matheus do Carmo','matheus.carmo@gmail.com','matheus123',323,2000),
                           (NULL,'Bruna','Bruna@gmail.com','1234',324,2000),
                           (NULL,'Bruno','Bruno@gmail.com','1234',325,2000),
                           (NULL,'Bruna','Bruna.Marquez@gmail.com','1234',326,2000),
                           (NULL,'Bruna','Bruninha@gmail.com','134',327,2000),
                           (NULL,'Junior','Junior@gmail.com','1234',328,2000),
                           (NULL,'Breno','Breno@gmail.com','1234',329,2000),
                           (NULL,'Gabriela','Gabriela@gmail.com','1234',330,2000),
                           (NULL,'Brenos','Brenos@gmail.com','1234',331,2001),
                           (NULL,'Debora','Debora@gmail.com','1234',332,2001),
                           (NULL,'Camila','Camila@gmail.com','1234',333,2001),
                           (NULL,'Jeferson','Jeferson@gmail.com','1234',334,2001),
                           (NULL,'Pedro','pedro1@ucl.com','pedrinho123',335,2001),
                           (NULL,'Wilker','wilker1@sptech.school','1234',336,2004),
                           (NULL,'Thais de frança','thais1@sptech.school','1234',337,2013),
                           (NULL,'Mauricio','mauricio1@sptech.school','123',338,2006),
                           (NULL,'Eduardo Begattini','eduardobegattini1@gmail.com','54321',339,2016),
                           (NULL,'Mateus','mateus1@sptech.school','12345',340,2004),
                           (NULL,'Luigi','lulu1@gmail.com','12345',341,2000),
                           (NULL,'Leonardo Pinho','leonardo.pinho1@sptech.school','1234',342,2004),
                           (NULL,'Gustavo','gusta.goncalves1@hotmail.com','12345',343,2002),
                           (NULL,'Irineu','irineu1@gmail.com','1234',344,2016),
                           (NULL,'Gabriel Bordin','biel1@gmail.com','123',345,2014),
                           (NULL,'Nicolas','nick1@gmail.com','1122',346,2013),
                           (NULL,'Rafa','rafael.oliveira1@sptech.school','rafa',347,2006),
                           (NULL,'Ruy','ruy1@gmail.com','1234',348,2002),
                           (NULL,'Michelly','Michelly1@gmail.com','1234',349,2002),
                           (NULL,'Rafaela','rafaela.dias1@sptech.school','123',350,2000),
                           (NULL,'Gabriel','gabriel.antonio1@hotmail.com','ascd123',351,2007),
                           (NULL,'Patrick','patrick1@gmail.com','1234',352,2007),
                           (NULL,'Lourenzo Mota','lourenzo.silva1@gmail.com','1234567',353,2000),
                           (NULL,'Ezequiel','ezequie1l@gmail.com','0907',354,2004),
                           (NULL,'Vitinho','victorlag1e@gmail.com','ODLA',355,2001),
                           (NULL,'Fabio','fa1bo@gmail.com','123',356,2002),
                           (NULL,'Kaique','ka1ique@gmail.com','1234',357,2001),
                           (NULL,'Matheus do Carmo','matheu1s.carmo@gmail.com','matheus123',358,2000),
                           (NULL,'Bruna','Brun1a@gmail.com','1234',359,2000),
                           (NULL,'Bruno','Brun1o@gmail.com','1234',360,2000),
                           (NULL,'Bruna','Brun1a.Marquez@gmail.com','1234',361,2000),
                           (NULL,'Bruna','Bruni1nha@gmail.com','134',362,2000),
                           (NULL,'Junior','Ju1nior@gmail.com','1234',363,2000),
                           (NULL,'Breno','Bre1no@gmail.com','1234',364,2000),
                           (NULL,'Gabriela','Ga1briela@gmail.com','1234',365,2000),
                           (NULL,'Brenos','Breno1s@gmail.com','1234',366,2001),
                           (NULL,'Debora','Debora1@gmail.com','1234',367,2001),
                           (NULL,'Camila','Camil1a@gmail.com','1234',368,2001),
                           (NULL,'Jeferson','Jefverson@gmail.com','1234',369,2001),
                           (NULL,'Pedro','pedr2o@ucl.com','pedrinho123',370,2001),
                           (NULL,'Wilker','wil2ker@sptech.school','1234',371,2004),
                           (NULL,'Thais de frança','thai2s@sptech.school','1234',372,2013),
                           (NULL,'Mauricio','mauric2io@sptech.school','123',373,2006),
                           (NULL,'Eduardo Begattini','eduardo2begattini@gmail.com','54321',374,2016),
                           (NULL,'Mateus','mat2eus@sptech.school','12345',375,2004),
                           (NULL,'Luigi','lulu2@gmail.com','12345',376,2000),
                           (NULL,'Leonardo Pinho','le2onardo.pinho@sptech.school','1234',377,2004),
                           (NULL,'Gustavo','gusta.gon2calves@hotmail.com','12345',378,2002),
                           (NULL,'Irineu','irine2u@gmail.com','1234',379,2016),
                           (NULL,'Gabriel Bordin','bi2el@gmail.com','123',380,2014),
                           (NULL,'Nicolas','nic2k@gmail.com','1122',381,2013),
                           (NULL,'Rafa','rafael2.oliveira@sptech.school','rafa',382,2006),
                           (NULL,'Ruy','ruy2@gmail.com','1234',383,2002),
                           (NULL,'Michelly','Mic2helly@gmail.com','1234',384,2002),
                           (NULL,'Rafaela','rafae2la.dias@sptech.school','123',385,2000),
                           (NULL,'Gabriel','gabrivel.antonio@hotmail.com','ascd123',386,2007),
                           (NULL,'Patrick','patric2k@gmail.com','1234',387,2007),
                           (NULL,'Lourenzo Mota','lourenzo22.silva@gmail.com','1234567',388,2000),
                           (NULL,'Ezequiel','ezequiel2@gmail.com','0907',389,2004),
                           (NULL,'Vitinho','victorlag2e@gmail.com','ODLA',390,2001),
                           (NULL,'Fabio','fabo2@gmail.com','123',391,2002),
                           (NULL,'Kaique','kai2que@gmail.com','1234',392,2001),
                           (NULL,'Matheus do Carmo','matvheus.carmo@gmail.com','matheus123',393,2000),
                           (NULL,'Bruna','Brunva@gmail.com','1234',394,2000),
                           (NULL,'Bruno','Brun2o@gmail.com','1234',395,2000),
                           (NULL,'Bruna','Brun2a.Marquez@gmail.com','1234',396,2000),
                           (NULL,'Bruna','Brun2inha@gmail.com','134',397,2000),
                           (NULL,'Junior','Jun2ior@gmail.com','1234',398,2000),
                           (NULL,'Breno','Brenvo@gmail.com','1234',399,2000),
                           (NULL,'Gabriela','G2abriela@gmail.com','1234',400,2000),
                           (NULL,'Brenos','Bren2os@gmail.com','1234',401,2001),
                           (NULL,'Debora','Debo2ra@gmail.com','1234',402,2001),
                           (NULL,'Camila','Cami2la@gmail.com','1234',403,2001),
                           (NULL,'Jeferson','Je2ferson@gmail.com','1234',404,2001),
                           (NULL,'Pedro','pedr3o@ucl.com','pedrinho123',405,2002),
                           (NULL,'Wilker','wil3ker@sptech.school','1234',406,2002),
                           (NULL,'Thais de frança','th3ais@sptech.school','1234',407,2002),
                           (NULL,'Mauricio','ma3urici3o@sptech.school','123',408,2002),
                           (NULL,'Eduardo Begattini','eduar3dobegattini@gmail.com','54321',409,2002),
                           (NULL,'Mateus','mate3us@sptech.school','12345',410,2004),
                           (NULL,'Luigi','lul3u@gmail.com','12345',411,2004),
                           (NULL,'Leonardo Pinho','leovnardo.pinho@sptech.school','1234',412,2004),
                           (NULL,'Gustavo','gusta.goncal3ves@hotmail.com','12345',413,2004),
                           (NULL,'Irineu','irin3eu@gmail.com','1234',414,2004),
                           (NULL,'Gabriel Bordin','bi3el@gmail.com','123',415,2004),
                           (NULL,'Nicolas','nic3k@gmail.com','1122',416,2004),
                           (NULL,'Rafa','rafael.3oliveira@sptech.school','rafa',417,2013),
                           (NULL,'Ruy','ruy@gma3il.com','1234',418,2013),
                           (NULL,'Michelly','Mi3chelly@gmail.com','1234',419,2013),
                           (NULL,'Rafaela','raf3aela.dias@sptech.school','123',420,2013),
                           (NULL,'Gabriel','gabriel.antonio@hotmail.com','ascd123',421,2013),
                           (NULL,'Patrick','patr3ick@gmail.com','1234',422,2013),
                           (NULL,'Lourenzo Mota','lourenzo.silva@gmail.com','1234567',423,2013),
						   (NULL,'Pedro','pedr4o@ucl.com','pedrinho123',424,2013),
                           (NULL,'Wilker','wilker@sptech.school','1234',425,2013),
                           (NULL,'Thais de frança','thais@sptech.school','1234',426,2013),
                           (NULL,'Mauricio','mauricio@sptech.school','123',427,2013),
                           (NULL,'Eduardo Begattini','eduardobegattini@gmail.com','54321',428,2013),
                           (NULL,'Breno','Breno@gmail.com','1234',429,2004),
                           (NULL,'Gabriela','Gabriela@gmail.com','1234',430,2004),
                           (NULL,'Brenos','Brenos@gmail.com','1234',431,2004),
                           (NULL,'Debora','Debora@gmail.com','1234',432,2004),
                           (NULL,'Camila','Camila@gmail.com','1234',433,2004),
                           (NULL,'Jeferson','Jeferson@gmail.com','1234',434,2004),
                           (NULL,'Pedro','ped5ro@ucl.com','pedrinho123',435,2004),
                           (NULL,'Wilker','wilker@sptech.school','1234',436,2004),
                           (NULL,'Thais de frança','thais@sptech.school','1234',437,2004),
                           (NULL,'Mauricio','mauricio@sptech.school','123',438,2004),
                           (NULL,'Eduardo Begattini','eduardobegattini@gmail.com','54321',439,2004),
                           (NULL,'Mateus','mateus@sptech.school','12345',440,2004);
                           
SELECT * FROM usuario;

CREATE TABLE TIMESUCL (
idTimeUCL INT PRIMARY KEY AUTO_INCREMENT,
nomeTime VARCHAR(45)
)auto_increment = 2000;

INSERT INTO TIMESUCL VALUES (NULL,'Real Madrid'),
                            (NULL,'Milan'),
                            (NULL,'Liverpool'),
                            (NULL,'Bayer Munchin'),
                            (NULL,'FC Barcelona'),
                            (NULL,'Ajax'),
                            (NULL,'Manchester United'),
                            (NULL,'Internazionale'),
                            (NULL,'Juventos'),
                            (NULL,'Benfica'),
                            (NULL,'Porto'),
                            (NULL,'Chealsea'),
                            (NULL,'Feyenoord'),
                            (NULL,'Borrusia Dortmound'),
                            (NULL,'Celtic'),
                            (NULL,'Hamburgo'),
                            (NULL,'Aston Villa'),
                            (NULL,'PSV'),
                            (NULL,'Estrela Vermelha'),
                            (NULL,'Steaute'),
                            (NULL,'Olympique de Marseillie'),
                            (NULL,'Nottingham Forest');
SELECT * FROM TIMESUCL;                        
SELECT TIMESUCL.nomeTime, count(usuario.idUsuario) AS 'Quantidade de Votos' FROM Usuario JOIN TIMESUCL ON fkTimeUCL = idTimeUCL GROUP BY TIMESUCL.nomeTime; 

CREATE TABLE Contato (
idContato INT PRIMARY KEY auto_increment,
nome VARCHAR(45),
email VARCHAR(45),
mensagem VARCHAR (300)
)auto_increment= 1000;

INSERT INTO Contato VALUES (NULL,'Wilker','wilker@spetch.school','Site esta ficando execelente parabéns pelo projeto');
SELECT * FROM Contato;

CREATE TABLE TimeCoracao(
idTimeC INT PRIMARY KEY AUTO_INCREMENT,
nomeTimeC VARCHAR (45)
)AUTO_INCREMENT=300;

INSERT INTO TimeCoracao VALUES (NULL,'São Paulo'),                                
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino'),
                               (NULL,'Corinthians'),
                               (NULL,'Palmeiras'),
                               (NULL,'Barcelona'),
                               (NULL,'Flamengo'),
                               (NULL,'Criciuma'),
                               (NULL,'Borussia Dortmound'),
                               (NULL,'Corinthians'),
                               (NULL,'Vasco da Gama'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Santos'),
                               (NULL,'Flamengo'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Santos'),
                               (NULL,'Santos'),
                               (NULL,'São Paulo'), 
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino'),
                               (NULL,'Corinthians'),
                               (NULL,'Palmeiras'),
                               (NULL,'Barcelona'),
                               (NULL,'Flamengo'),
                               (NULL,'Criciuma'),
                               (NULL,'Borussia Dortmound'),
                               (NULL,'Corinthians'),
                               (NULL,'Vasco da Gama'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Santos'),
                               (NULL,'Flamengo'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Santos'),
                               (NULL,'Santos'),                 
                               (NULL,'São Paulo'), 
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino'),
                               (NULL,'Corinthians'),
                               (NULL,'Palmeiras'),
                               (NULL,'Barcelona'),
                               (NULL,'Flamengo'),
                               (NULL,'Criciuma'),
                               (NULL,'Borussia Dortmound'),
                               (NULL,'Corinthians'),
                               (NULL,'Vasco da Gama'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Santos'),
                               (NULL,'Flamengo'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Flamengo'),
                               (NULL,'Santos'),
                               (NULL,'Santos'),
                               (NULL,'São Paulo'), 
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino'),
                               (NULL,'Corinthians'),
                               (NULL,'Palmeiras'),
                               (NULL,'Barcelona'),
                               (NULL,'Flamengo'),
                               (NULL,'Criciuma'),
                               (NULL,'Borussia Dortmound'),
                               (NULL,'São Paulo'), 
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino'),
                               (NULL,'Corinthians'),
                               (NULL,'Palmeiras'),
                               (NULL,'Barcelona'),
                               (NULL,'Flamengo'),
                               (NULL,'Criciuma'),
                               (NULL,'Borussia Dortmound'),
                               (NULL,'Corinthians'),
                               (NULL,'Vasco da Gama'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Corinthians'),
                               (NULL,'Santos'),
                               (NULL,'Flamengo'),
                               (NULL,'São Paulo'), 
                               (NULL,'São Paulo'),
                               (NULL,'São Paulo'),
                               (NULL,'Corinthians'),
                               (NULL,'Time Feminino');
                               
SELECT * FROM TimeCoracao;                           